a = input('Digite algo: ')
print('O tipo de primitivo de {} é '.format(a), type(a))
print('Só tem espaços?', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maiúscula? ', a.isupper())
print('Está em minúsculo? ', a.islower())
print('Está capitalizada? ', a.istitle())
