times = ('Sao Paulo', 'Palmeiras', 'Corinthias', 'Botafogo', 'Flamengo', 'Vasco', 'Fluminense', 'Chapecoense', 'Coritiba', 'Parana', 'Sampaio Correa', 'Moto clube', 'Paisandu', 'Remo', 'Gremio', 'Internacional')
print(f'Os times da 1ª divisão do brasileirão são: {times}')
print('-=' * 50)
print(f'Os cinco primeiros colocados são: {times[0:5]}')
print('-=' * 50)
print(f'Os últimos quatro colocados são: {times[-4:]}')
print('-=' * 50)
print(f'Os times em ordem alfabética são: {sorted(times)}')
print('-=' * 50)
print(f'O Chapecoense está na posição: {times.index("Chapecoense") + 1}')
